# Generated by Django 4.1.6 on 2023-02-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileHeader",
            fields=[
                ("file_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=100, unique=True)),
                ("file_url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Uploads",
            fields=[
                ("row_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(default=0)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("std", models.IntegerField(blank=True, null=True)),
                ("date", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.fileheader"
                    ),
                ),
            ],
        ),
    ]
